version: "2"
linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - copyloopvar
    - exhaustive
    - unconvert
    - unparam
    - wastedassign
    - predeclared
    - gosec
    - gocritic
    - nonamedreturns

    # These looked promising but weren't worth the trouble:
    # - gomnd # too strict
    # - tagliatelle # naming, not struct tag validness..

    # full list available by running: $ golangci-lint linters  settings:
  settings:
    gocritic:
      disabled-checks:
        - ifElseChain
    gosec:
      excludes:
        - G115
    staticcheck:
      checks:
        - all
        - '-ST1001' # "Dot imports are discouraged."
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - .+\.gen\.go$
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - .+\.gen\.go$
      - third_party$
      - builtin$
      - examples$
