
issues:
  exclude-files:
    # golangci-lint doesn't recognize our generated files (*.gen.go)
    - ".+\\.gen\\.go$"

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused # everything below this is in addition to enabled-by-default

    - goimports
    - copyloopvar
    - exhaustive
    - unconvert
    - unparam
    - wastedassign
    - predeclared
    - gosec
    - gocritic
    - nonamedreturns

    # These looked promising but weren't worth the trouble:
    # - gomnd # too strict
    # - tagliatelle # naming, not struct tag validness..

    # full list available by running: $ golangci-lint linters

linters-settings:
  gocritic:
    disabled-checks:
    - ifElseChain # false positives (some if-else chains with "short ifs" look more cumbersome rewritten)
