# Minimal Travis conf to bootstrap Turbo Bob

sudo: required
services: docker
language: minimal
script:
  - curl --fail --location --output bob https://dl.bintray.com/function61/turbobob/20180830_1256_aa46182c2c42934d/bob_linux-amd64 && chmod +x bob
  - CI_REVISION_ID="$TRAVIS_COMMIT" ./bob build --publish-artefacts
